#include<iostream>
#include<time.h>
#include<cstdlib>
using namespace std;
void game(int n);
int main()
{
	int n;
	cout << " enter a random number" << endl;
	cin >> n;
	game(n);
	return 0;
}
void game(int n)
{
	int a, b, c, sum;
	sum = 0;
	a = time(0);
	srand(a);
	cout << "the random numbers generated by function are " << endl;
	for (int i = 0; i < 2; i++)
	{
		b = rand();
		c = b % 1000;
		cout << c << "\t" << endl;
		sum += c;
	}
	cout << sum << endl;
	if (sum == n)
	{
		cout << "congratulation" << endl;
	}
	else
	{
		cout << "try again" << endl;
	}
	cout << "the number entered by user is " << n << endl;
}
